# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
# author: PR作成者
addAssignees: author

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - takamine-wataruhogehoge #まちがえてみる

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0

# A list of assignees, overrides reviewers if set
# assignees:
#  - hasegawa-asami
#  - popotyoro
#  - koizuka-kazuyuki

# A number of assignees to add to the pull request
# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
# numberOfAssignees:2

# A list of keywords to be skipped the process that add reviewers if pull requests include it
# skipKeywords:
#   - wip

